apiVersion: apps/v1
kind: Deployment
metadata:
  name: plantsbywebsphereee6v2-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: plantsbywebsphereee6v2-operator
  template:
    metadata:
      labels:
        name: plantsbywebsphereee6v2-operator
    spec:
      serviceAccountName: plantsbywebsphereee6v2-operator
      containers:
        - name: plantsbywebsphereee6v2-operator
          image: openliberty/operator:0.3.0
          command:
          - open-liberty-operator
#          imagePullPolicy: Always
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "open-liberty-operator"
